version: "3"

services:

  mongodb:
    image: mongo
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    volumes:
      - mongo-data:/data/db 

  backend:
    image: assignment-backend
    restart: always
    ports:
      - 8080:8080
    environment:
      - MONGODB_HOST=mongodb
      - MONGODB_PORT=27017
      - MONGODB_DATABASE=mydb
      - MONGODB_USERNAME=root
      - MONGODB_PASSWORD=example
      - MONGODB_AUTHENTICATION_DATABASE=admin
  
  frontend:
    image: assignment-frontend
    restart: always
    ports:
      - 3000:80

volumes:
  mongo-data:
